name: ntext-cli

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true

            - name: Build
              run: cargo build --all --release && strip target/release/ntext-cli 

            - name: Release
              uses: softprops/actions-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      target/release/ntext-cli
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            

